Prism/Controllers/DataAnalyzeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prism.Models;
using System.Web.Routing;
using System.Net;
using System.IO;

namespace Prism.Controllers
{
    public class DataAnalyzeController : Controller
    {

        public ActionResult HPUTrend()
        {
            if (!MachineUserMap.IsLxEmployee(Request.UserHostName, null, 7, "HPUTrend"))
            {
                return RedirectToAction("Index", "Main");
            }

            ViewBag.defaultserial = "";
            var syscfg = CfgUtility.GetSysConfig(this);
            if (syscfg.ContainsKey("HPUTRENDSERIAL"))
            { ViewBag.defaultserial = syscfg["HPUTRENDSERIAL"]; }
            return View();
        }

        private List<double> GetHPUDataBySerial(string serial,List<string> xaxis,List<HPUMainData> srcdata)
        {
            var yieldhpulist = new List<double>();
            if (serial.Contains("-FG") || serial.Contains("- FG"))
            {
                foreach (var q in xaxis)
                {
                    var temphpu = 0.0;
                    foreach (var data in srcdata)
                    {
                        if (string.Compare(data.Serial.Replace("-SFG", "").Replace("- SFG", "").Replace("-FG", "").Replace("- FG", ""), serial.Replace("-FG", "").Replace("- FG", "")) == 0
                            && string.Compare(data.Quarter, q) == 0
                            && (data.Serial.Contains("-SFG") || data.Serial.Contains("- SFG")))
                        {
                            if (data.Serial.ToUpper().Contains("WIRE") && !data.Serial.ToUpper().Contains("WIRELESS"))
                            {
                                temphpu += 2.0 * Convert.ToDouble(data.YieldHPU);
                            }
                            else
                            {
                                temphpu +=  Convert.ToDouble(data.YieldHPU);
                            }
                        }
                        if (string.Compare(data.Serial.Replace("-SFG", "").Replace("- SFG", "").Replace("-FG", "").Replace("- FG", ""), serial.Replace("-FG", "").Replace("- FG", "")) == 0
                            && string.Compare(data.Quarter, q) == 0
                            && (data.Serial.Contains("-FG") || data.Serial.Contains("- FG")))
                        {
                            temphpu += Convert.ToDouble(data.YieldHPU);
                        }
                    }
                    yieldhpulist.Add(Math.Round(temphpu,4));
                }
            }
            else
            {
                foreach (var q in xaxis)
                {
                    foreach (var data in srcdata)
                    {
                        if (string.Compare(data.Serial, serial) == 0 && string.Compare(data.Quarter, q) == 0)
                        {
                            yieldhpulist.Add(Math.Round(Convert.ToDouble(data.YieldHPU),4));
                        }
                    }
                }
            }

            return yieldhpulist;
        }

        private List<double> GetHPUReduction(List<double> yieldhpulist)
        {
            var hpureduction = new List<double>();
            hpureduction.Add(0.0);
            for (var idx = 1; idx < yieldhpulist.Count; idx++)
            {
                hpureduction.Add(Math.Round((yieldhpulist[idx - 1] - yieldhpulist[idx]) / yieldhpulist[idx - 1] * 100.0, 2));
            }
            return hpureduction;
        }

        public JsonResult HPUTrendData()
        {
            var serial = Request.Form["serial"];
            var srcdata = HPUMainData.RetrieveHPUDataBySerial(serial);
            var syscfg = CfgUtility.GetSysConfig(this);
            var defseriallist = serial.Split(new string[] { ";" }, StringSplitOptions.RemoveEmptyEntries);

            var hpuarray = new List<object>();
            try {
                if (srcdata.Count > 0)
                {
                    var seriallist = new List<string>();
                    var serialdict = new Dictionary<string, bool>();
                    foreach (var item in srcdata)
                    {
                        if (!item.Serial.Contains("-SFG") && !item.Serial.Contains("- SFG"))
                        {
                            if (!serialdict.ContainsKey(item.Serial))
                            {
                                serialdict.Add(item.Serial,true);
                                seriallist.Add(item.Serial);
                            }
                        }
                    }//get serials

                    foreach (var sitem in seriallist)
                    {
                        var defserial = "";
                        foreach (var defs in defseriallist)
                        {
                            if (sitem.Contains(defs))
                            {
                                defserial = defs;
                                break;
                            }
                        }

                        var xaxis = new List<string>();
                        foreach (var data in srcdata)
                        {
                            if (string.Compare(data.Serial, sitem) == 0)
                            {
                                xaxis.Add(data.Quarter);
                            }
                        }//get quarter x list

                        if (xaxis.Count == 1)
                        { continue; }

                        var yieldhpulist = GetHPUDataBySerial(sitem, xaxis, srcdata);
                        //var hpureduction = GetHPUReduction(yieldhpulist);

                        var maxhpu = 0.0;
                        foreach (var yhp in yieldhpulist)
                        { if (yhp > maxhpu) { maxhpu = yhp; } }

                        var defaultguideline = 5.0;
                        if (syscfg.ContainsKey(defserial + "-GUIDELINE"))
                        {
                            defaultguideline = Convert.ToDouble(syscfg[defserial + "-GUIDELINE"]);
                        }

                        var targetline = new List<double>();
                        var rate = 1.0;
                        foreach (var hpu in yieldhpulist)
                        {
                            targetline.Add(Math.Round(rate * yieldhpulist[0],3));
                            rate = rate * (1-defaultguideline*0.01);
                        }

                        var title = sitem.Replace("-FG", "").Replace("- FG", "") + " HPU";

                        var oneobj = new
                        {
                            id = title.Replace(" ", "_") + "_line",
                            title = title,
                            xAxis = new { data = xaxis },
                            maxhpu = maxhpu,
                            yieldhpu = new { name = "Actual HPU", data = yieldhpulist },
                            hpureductiontarget = new { name = "HPU Reduce "+ defaultguideline.ToString("0")+ "% Target", data = targetline },
                            url = "/DataAnalyze/SerialHPU?defaultserial=" + sitem.Split(new string[] { "-FG", "- FG" },StringSplitOptions.RemoveEmptyEntries)[0]
                        };

                        hpuarray.Add(oneobj);

                    }//get chart data from each serial

                }
            } catch (Exception ex) { }




            var ret = new JsonResult();
            ret.MaxJsonLength = Int32.MaxValue;
            ret.Data = new
            {
                success = true,
                hpuarray = hpuarray
            };
            return ret;
        }


        public ActionResult DepartmentHPU()
        {
            if (!MachineUserMap.IsLxEmployee(Request.UserHostName, null, 7, "DepartmentHPU"))
            {
                return RedirectToAction("Index", "Main");
            }

            var productlines = HPUMainData.GetAllProductLines();
            ViewBag.productlines = CreateSelectList(productlines, "");

            var quarterlist = HPUMainData.GetAllQuarters();
            quarterlist.Insert(0, FinanceQuarter.CURRENTQx);
            ViewBag.quarterlist = CreateSelectList(quarterlist, "");

            return View();
        }

        public JsonResult DepartmentHPUData()
        {
            var productline = Request.Form["pdline"];
            var fquarter = Request.Form["quarter"];

            if (string.Compare(fquarter, FinanceQuarter.CURRENTQx) == 0)
            {
                var now = DateTime.Now;
                var year = ExternalDataCollector.GetFYearByTime(now);
                var quarter = ExternalDataCollector.GetFQuarterByTime(now);
                fquarter = year + " " + quarter;
            }

            var data = HPUMainData.RetrieveHPUData(productline,fquarter);
            var ret = new JsonResult();
            ret.MaxJsonLength = Int32.MaxValue;
            ret.Data = new
            {
                success = true,
                data = data
            };
            return ret;
        }


        private double Convert2Double(string val)
        {
            try
            {
                return Convert.ToDouble(val);
            }
            catch (Exception ex) {
                return 0.0;
            }
        }


        public ActionResult SerialHPU(string defaultserial)
        {
            if (!MachineUserMap.IsLxEmployee(Request.UserHostName, null, 7, "SerialHPU"))
            {
                return RedirectToAction("Index", "Main");
            }

            ViewBag.defaultserial = "";
            if (!string.IsNullOrEmpty(defaultserial))
            {
                ViewBag.defaultserial = defaultserial;
            }
            return View();
        }

        public JsonResult GetAllSerial()
        {
            var slist = HPUMainData.RetrieveAllSerial();
            var ret = new JsonResult();
            ret.Data = new

Prism/Views/DataAnalyze/CostCenterScrap.cshtml
@{
    ViewBag.Title = "Cost Center Scrap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link type="text/css" rel="stylesheet" href="~/Scripts/jquery-autocomplete/jquery.auto-complete.css" />
<link type="text/css" rel="stylesheet" href="~/Content/SCRAP-RATE.css" />
<link type="text/css" rel="stylesheet" href="~/Scripts/bootstrap-tagsinput/bootstrap-tagsinput.css" />


<script type="text/javascript" src="~/Scripts/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-tagsinput/bootstrap3-typeahead.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-autocomplete/jquery.auto-complete.min.js"></script>
<script type="text/javascript" src="~/Scripts/Scrap-Rate.js"></script>
<script type="text/javascript">
        $(function(){
            SCRAPRATE.COSTCENTINIT();
        })
</script>

<div class="row">
    <div class="nav navbar-nav navbar-left">
        <img src="~/Content/images/Yield.png" style="height:40px; width:40px">
    </div>
    <div class="nav navbar-nav navbar-left">
        <ol class="breadcrumb" style="width:600px">
            <li><a data-toggle="tooltip" title="Goto Main Page" href="/Main/Index">Main</a></li>
            <li class="active">Cost Center Scrap</li>
        </ol>
    </div>
</div>

<div class="row">
    <nav class="col-xs-2 nav-sidebar">
        <ul class="nav">
            <li>
                <a href="/DataAnalyze/DepartmentScrap">
                    <span class="item-show">Department Scrap</span>
                </a>
            </li>
            <li class="active">
                <a href="/DataAnalyze/CostCenterScrap">
                    <span class="item-show">Cost Center Scrap</span>
                </a>
            </li>
            <li>
                <a href="/DataAnalyze/ProductScrap">
                    <span class="item-show">Product Scrap</span>
                </a>
            </li>
        </ul>
    </nav>
    <div class="col-xs-10">
        <div class="v-container">
            <div class="v-filter">
                <div class="row row-margin">
                    <label class="col-xs-2">Finance Year</label>
                    <div class="col-xs-3">
                        @Html.DropDownList("fyearlist", null, new { @id = "fyearlist", @class = "form-control" })
                    </div>
                    <div class="col-xs-1 text-center"></div>
                    <label class="col-xs-2">Finance Quarter</label>
                    <div class="col-xs-3">
                        @Html.DropDownList("fquarterlist", null, new { @id = "fquarterlist", @class = "form-control" })
                    </div>
                </div>
                <div class="row row-margin">
                    <label class="col-xs-2">Cost Center</label>
                    <div class="col-xs-8">
                        <input type="text" class="project-no" data-provide="typeahead"
                               id="pj-no" name="pj-no" autocomplete="off" placeholder="Cost Center" value="@ViewBag.carepjlist">
                    </div>
                    <div class="col-xs-1 box-search" style="padding-left:0">
                        <input type="button" class="btn btn-success" name="btn-search" id="btn-search" value="Search">
                    </div>
                </div>
            </div>
            <div class="v-content">
            </div>
            <span id="loadcomplete" name="loadcomplete" class="hide">FALSE</span>
        </div>
    </div>
    <div class="hidden">
        <a id="exportLink"></a>
    </div>
</div>

<div class="modal fade" id="report-alert" tabindex="-1" role="dialog" style="margin-top:10%">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Report</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" name="reportid" id="reportid">
                <div class="row" style="padding-left:10px;padding-bottom:10px;">
                    <a id="productscrap" name="productscrap" href="#" class="btn btn-success" target="_blank">Product Scrap</a>
                </div>
                <div class="row" style="padding:10px;">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title" style="display:inline-block">Report</h3>
                            <span id="editreport" name="editreport" class="glyphicon glyphicon-edit" style="display:inline-block;float:right;color:#428bca;font-size:22px;cursor:pointer;"></span>
                        </div>
                        <div class="panel-body">
                            <div class="row" id="rc-info" style="padding-left:10px;padding-right:10px;">Report</div>
                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-xs-3 col-xs-offset-6">
                                    Reporter: <span id="rc-reporter">System</span>
                                </div>
                                <div class="col-xs-3">
                                    <span id="rc-datetime">@DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="btn-wf-cancel" name="btn-wf-cancel" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Prism/Views/DataAnalyze/DepartmentHPU.cshtml
@{
    ViewBag.Title = "Department HPU";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link type="text/css" rel="stylesheet" href="~/Scripts/jquery-autocomplete/jquery.auto-complete.css" />
<link type="text/css" rel="stylesheet" href="~/Content/SCRAP-RATE.css" />
<link type="text/css" rel="stylesheet" href="~/Scripts/bootstrap-tagsinput/bootstrap-tagsinput.css" />


<script type="text/javascript" src="~/Scripts/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-tagsinput/bootstrap3-typeahead.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-autocomplete/jquery.auto-complete.min.js"></script>
<script type="text/javascript" src="~/Scripts/HPU.js"></script>
<script type="text/javascript">
        $(function(){
            HPU.DEPARTMENTINIT();
        })
</script>

<input class="hide" type="text" id="hidetitle" name="hidetitle" value="HPU / DEPARTMENT HPU">

@*<div class="row">
    <div class="nav navbar-nav navbar-left">
        <img src="~/Content/images/Yield.png" style="height:40px; width:40px">
    </div>
    <div class="nav navbar-nav navbar-left">
        <ol class="breadcrumb" style="width:600px">
            <li><a data-toggle="tooltip" title="Goto Main Page" href="/Main/Index">Main</a></li>
            <li class="active">Department HPU</li>
        </ol>
    </div>
</div>*@

<div class="row">
    @*<nav class="col-xs-2 nav-sidebar">
        <ul class="nav">
            <li>
                <a href="/DataAnalyze/HPUTrend">
                    <span class="item-show">HPU Trend</span>
                </a>
            </li>
            <li class="active">
                <a href="/DataAnalyze/DepartmentHPU">
                    <span class="item-show">Department HPU</span>
                </a>
            </li>
            <li>
                <a href="/DataAnalyze/SerialHPU">
                    <span class="item-show">Serial HPU</span>
                </a>
            </li>
            <li>
                <a href="/DataAnalyze/PNHPU">
                    <span class="item-show">PN HPU</span>
                </a>
            </li>
        </ul>
    </nav>*@

    <div class="col-xs-12">
        <div class="v-container">
            <div class="v-filter">
                <div class="row row-margin">
                    <label class="col-xs-2">Product Line</label>
                    <div class="col-xs-2">
                        @Html.DropDownList("productlines", null, new { @id = "productlines", @class = "form-control" })
                    </div>
                    <div class="col-xs-1 text-center"></div>
                    <label class="col-xs-2">Finance Quarter</label>
                    <div class="col-xs-3">
                        @Html.DropDownList("quarterlist", null, new { @id = "quarterlist", @class = "form-control" })
                    </div>
                    <div class="col-xs-1 box-search" style="padding-left:0">
                        <input type="button" class="btn btn-success" name="btn-search" id="btn-search" value="Search">
                    </div>
                </div>
            </div>
            <div class="v-content">
                <table class="table table-hover  table-condensed table-striped" id="hpumaintable" style="margin-top:1%">
                    <caption class="tb-caption">DEPARTMENT HPU TABLE</caption>
                    <thead>
                        <tr>
                            <th></th>
                            <th>HPUCode</th>
                            <th>Product Line</th>
                            <th>Serial</th>
                            <th>Phase</th>
                            <th>PN</th>
                            @*<th>WH Measure</th>
                            <th>WH Collect</th>
                            <th>WH Checked</th>*@
                            <th>Yield HPU</th>
                            <th>Owner</th>
                            <th>Update Date</th>
                            @*<th>Form Make</th>*@
                            <th>Remark</th>
                        </tr>
                    </thead>
                    <tbody id="hpumaintableid"></tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="hidden">
        <a id="exportLink"></a>
    </div>
</div>

Prism/Views/DataAnalyze/DepartmentScrap.cshtml
@{
    ViewBag.Title = "Department Scrap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link type="text/css" rel="stylesheet" href="~/Scripts/jquery-autocomplete/jquery.auto-complete.css" />
<link type="text/css" rel="stylesheet" href="~/Content/SCRAP-RATE.css" />
<link type="text/css" rel="stylesheet" href="~/Scripts/bootstrap-tagsinput/bootstrap-tagsinput.css" />


<script type="text/javascript" src="~/Scripts/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-tagsinput/bootstrap3-typeahead.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-autocomplete/jquery.auto-complete.min.js"></script>
<script type="text/javascript" src="~/Scripts/Scrap-Rate.js"></script>
<script type="text/javascript">
        $(function(){
            SCRAPRATE.DEPARTMENTINIT();
        })
</script>

<div class="row">
    <div class="nav navbar-nav navbar-left">
        <img src="~/Content/images/Yield.png" style="height:40px; width:40px">
    </div>
    <div class="nav navbar-nav navbar-left">
        <ol class="breadcrumb" style="width:600px">
            <li><a data-toggle="tooltip" title="Goto Main Page" href="/Main/Index">Main</a></li>
            <li class="active">Department Scrap</li>
        </ol>
    </div>
</div>

<div class="row">
    <nav class="col-xs-2 nav-sidebar">
        <ul class="nav">
            <li class="active">
                <a href="/DataAnalyze/DepartmentScrap">
                    <span class="item-show">Department Scrap</span>
                </a>
            </li>
            <li>
                <a href="/DataAnalyze/CostCenterScrap">
                    <span class="item-show">Cost Center Scrap</span>
                </a>
            </li>
            <li>
                <a href="/DataAnalyze/ProductScrap">
                    <span class="item-show">Product Scrap</span>
                </a>
            </li>
            @*<li>
                <a href="/DataAnalyze/BRJOScrap">
                    <span class="item-show">BR/JO Scrap</span>
                </a>
            </li>*@
        </ul>
    </nav>
    <div class="col-xs-10">
        <div class="v-container">
            <div class="v-filter">
                <div class="row row-margin">
                    <label class="col-xs-2">Finance Year</label>
                    <div class="col-xs-2">
                        @Html.DropDownList("fyearlist", null, new { @id = "fyearlist", @class = "form-control" })
                    </div>
                    <div class="col-xs-1 text-center"></div>
                    <label class="col-xs-2">Finance Quarter</label>
                    <div class="col-xs-3">
                        @Html.DropDownList("fquarterlist", null, new { @id = "fquarterlist", @class = "form-control" })
                    </div>
                    <div class="col-xs-1 box-search" style="padding-left:0">
                        <input type="button" class="btn btn-success" name="btn-search" id="btn-search" value="Search">
                    </div>
                </div>
            </div>
            <div class="v-content">
            </div>
            <span id="loadcomplete" name="loadcomplete" class="hide">FALSE</span>
            <input class="hide" id="department" name="department" type="text" value="@ViewBag.Department"/>
        </div>
    </div>
    <div class="hidden">
        <a id="exportLink"></a>
    </div>
</div>

Prism/Views/DataAnalyze/ModifyReport.cshtml
@model Prism.Models.PrismComment

@{
    ViewBag.Title = "ModifyReport";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var isie = false;
    var ua = Request.UserAgent;
    if (ua.IndexOf("MSIE ") > 0 || ua.IndexOf("Trident/") > 0 || ua.IndexOf("Edge/") > 0)
    { isie = true; }
}

@if (!isie)
{
    <link href="~/Content/videorecorder.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/VideoRecorderJs-master/dist/VideoRecorderJS.min.js" type="text/javascript"></script>
    <script src="~/Scripts/MyVideoRecord.js" type="text/javascript"></script>

    <script type="text/javascript">
    $(function(){
        MyVideoRecord.Init();
    })
    </script>
}

<input class="hide" type="text" id="hidetitle" name="hidetitle" value="UPDATE REPORT">

@*<div class="row">
    <div class="nav navbar-nav navbar-left">
        <img src="~/Content/images/Report.png" style="height:35px; width:35px;margin-right: 15px;">
    </div>
    <div class="nav navbar-nav navbar-left">
        <ol class="breadcrumb" style="width:600px">
            <li class="active">Update Report</li>
        </ol>
    </div>
</div>*@

@if (Model != null)
{
    <div class="row">
        <div class="col-xs-12">&nbsp;</div>
    </div>

    <script src="../../ckeditor/ckeditor.js"></script>

    using (Html.BeginForm("ModifyWaferReport", "DataAnalyze", FormMethod.Post, new { enctype = "multipart/form-data",id="reportform",name= "reportform" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-xs-12">

                <div class="form-group">
                    <div MYTP="orange" style="font-family:'Arial Narrow';font-size:18px"><strong>&nbsp;&nbsp;Comment</strong></div>
                </div>

                <div class="form-group">
                    <div>
                        <textarea name="editor1" id="editor1" rows="10" cols="80">@Model.Comment</textarea>
                        <script>
                        CKEDITOR.replace('editor1', { htmlEncodeOutput: true, skin: 'moono-lisa' });
                        </script>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="col-xs-2">
                                <span class="btn btn-success btn-file" id="choosefile6">
                                    Editor Attachment <input type="file" name="file6" id="file6" runat="server" onchange="ShowFileNames6(this)" />
                                </span>
                            </div>
                            <div class="col-xs-1">
                                @if (!isie)
                                {
                                    <button class="btn btn-video maineditor-video" type="button"><span class="glyphicon glyphicon-facetime-video home-video-icon" style="text-align:center;"></span></button>
                                }
                            </div>
                            <div class="col-xs-1"></div>
                            <div class="col-xs-1"></div>
                            <div class="col-xs-7"></div>
                        </div>
                        <script type="text/javascript">
                        function ShowFileNames6(oFile) {
                            ajaxFileUpload();
                        }
                        function ajaxFileUpload() {
                            $.ajaxFileUpload
                            (
                                {
                                    url: '/userfiles/ImageUpload.ashx',
                                    secureuri: false,
                                    fileElementId: 'file6',
                                    dataType: 'HTML',
                                    success: function (data, status)
                                    {
                                        var wholeval = CKEDITOR.instances.editor1.getData() + data;
                                        CKEDITOR.instances.editor1.setData(wholeval);
                                    },
                                    error: function (e)
                                    {
                                        alert(e);
                                    }
                                }
                            )
                            return false;
                        }
                        </script>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <input class="form-control text-box single-line" value="@(Model.CommentID)" id="ReportId" name="ReportId" type="hidden" />
        </div>
        <div class="row">
            <input class="form-control text-box single-line" value="@(Model.CommentType)" id="HType" name="HType" type="hidden" />
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <div class="col-xs-3">
                        @*<input type="submit" value="Submit" class="btn btn-primary" />*@
                        <button class="btn btn-primary" onclick="SubmitReport()">Submit</button>
                    </div>
                    <div class="col-xs-9">
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                function SubmitReport()
                {
                    $("#reportform").submit();
                    window.close();
                }
            </script>
        </div>
    }

    if (!isie)
    {
        @Html.Partial("~/Views/Shared/_VideoRecordModal.cshtml")

        <script type="text/javascript">

        $(function () {
            $('body').on('click', '.m-video-upload', function () {
                $('.m-video-upload').addClass('hidden');
                $('.mc-play').removeClass('hidden');
                $(".m-video-loading").removeClass('hidden');

                var videoblob = MyVideoRecord.GetVideoBlob();
                var virec = MyVideoRecord.GetViRec();

                if (videoblob) {
                    var fd = new FormData();
                    fd.append('fname', 'myvideo.webm');
                    fd.append('data', videoblob);

                    $.ajax({
                        type: 'POST',
                        url: '/DataAnalyze/UploadWebmVideoData',
                        data: fd,
                        processData: false,
                        contentType: false
                    }).done(function (output) {
                        var wholeval = CKEDITOR.instances.editor1.getData() + output.data;
                        CKEDITOR.instances.editor1.setData(wholeval);

                        if (virec) {
                            //virec.clearRecording();
                            MyVideoRecord.StopTheCountDown();
                        }

                        //$('.mc-start').removeClass('hidden');
                        //$('#m-video-record').removeClass('hidden');
                        $('#m-video-play').addClass('hidden');
                        $('#m-video-play').attr('src', '');
                        $('#m-video-record').attr('src', '');
                        MyVideoRecord.SetViRec(null);
                        $('#modal-video').modal('hide');
                    });
                }
            })
    })
            </script>
    }


}